// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Implements the ParameterOptimizationAssistant flow, which suggests optimal parameter settings
 *   for a 3D scene based on complexity, rendering method, and desired framerate.
 *
 * - parameterOptimizationAssistant - A function that handles the parameter optimization process.
 * - ParameterOptimizationInput - The input type for the parameterOptimizationAssistant function.
 * - ParameterOptimizationOutput - The return type for the parameterOptimizationAssistant function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ParameterOptimizationInputSchema = z.object({
  sceneComplexity: z
    .string()
    .describe(
      'A description of the scene complexity (e.g., number of objects, polygon count, texture resolution).'
    ),
  renderingMethod: z
    .string()
    .describe(
      'The rendering method used (e.g., ray tracing, rasterization, path tracing).'
    ),
  desiredFramerate: z
    .number()
    .describe('The desired framerate in frames per second (FPS).'),
  existingParameters: z
    .string()
    .describe(
      'A description of the existing parameter settings, including specific values and their effects.'
    ),
});
export type ParameterOptimizationInput = z.infer<typeof ParameterOptimizationInputSchema>;

const ParameterOptimizationOutputSchema = z.object({
  suggestedSettings: z
    .string()
    .describe(
      'Suggested optimal parameter settings based on the input factors, including specific values and justifications for each setting.'
    ),
});
export type ParameterOptimizationOutput = z.infer<typeof ParameterOptimizationOutputSchema>;

export async function parameterOptimizationAssistant(
  input: ParameterOptimizationInput
): Promise<ParameterOptimizationOutput> {
  return parameterOptimizationFlow(input);
}

const parameterOptimizationPrompt = ai.definePrompt({
  name: 'parameterOptimizationPrompt',
  input: {schema: ParameterOptimizationInputSchema},
  output: {schema: ParameterOptimizationOutputSchema},
  prompt: `You are an expert 3D graphics performance tuner. Based on the following information, suggest optimal parameter settings to achieve the best performance.

Scene Complexity: {{{sceneComplexity}}}
Rendering Method: {{{renderingMethod}}}
Desired Framerate: {{{desiredFramerate}}}
Existing Parameters: {{{existingParameters}}}

Consider the trade-offs between visual quality and performance when making your suggestions. Provide specific values for each parameter and explain the reasoning behind your choices.

Suggested Settings:`,
});

const parameterOptimizationFlow = ai.defineFlow(
  {
    name: 'parameterOptimizationFlow',
    inputSchema: ParameterOptimizationInputSchema,
    outputSchema: ParameterOptimizationOutputSchema,
  },
  async input => {
    const {output} = await parameterOptimizationPrompt(input);
    return output!;
  }
);
